name: 'Test Report'
on:
  workflow_run:
    workflows: ['tests']
    types:
      - completed
jobs:
  report:
    permissions:
      checks: write
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: TestResults
        name: Unit Tests
        path: '*.trx'
        reporter: dotnet-trx